# Generated by Django 3.1.5 on 2021-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='card_color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=10),
        ),
    ]
