# Generated by Django 3.1.5 on 2021-01-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_message_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='members',
            field=models.ManyToManyField(blank=True, to='boxes.Member'),
        ),
    ]
